name: 部署文档

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

env:
  GITHUB_NAME: arthurfsy2
  GITHUB_EMAIL: fsyflh@gmail.com

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: 设置Python版本
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: 'src/.vuepress/public/scripts/requirements.txt'

      - name: 安装依赖
        run: |
          pip install -r src/.vuepress/public/scripts/requirements.txt

      - name: 生成图云
        run: |
          python src/.vuepress/public/scripts/wordcloud2SvgGA.py

      - name: 提交更新图云
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          mkdir -p src/.vuepress/public/assets/img
          mv wordcloud.svg src/.vuepress/public/assets/img/
          git add .
          git commit -m "Moved to src/.vuepress/public/assets/img/wordcloud.svg"
          git push

      - name: 设置 Node.js 和 Yarn
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 20.x
      - run: npm install -g yarn

      - name: 安装依赖
        run: yarn install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          yarn run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: src/.vuepress/dist