name: 更新Postcrossing的markdown文件

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - main

env:
  GITHUB_NAME: arthurfsy2
  GITHUB_EMAIL: fsyflh@gmail.com
  PUSH_TO_GITHUB: true

jobs:
  sync:
    name: 同步
    runs-on: ubuntu-latest
    outputs:
      PUSH_TO_GITHUB: ${{ steps.push.outputs.PUSH_TO_GITHUB }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 设置Python版本
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: 'src/.vuepress/public/scripts/requirements.txt'

      - name: 安装python依赖
        run: |
          pip install -r src/.vuepress/public/scripts/requirements.txt

      - name: 下载markdown
        run: |
          python src/.vuepress/public/scripts/updatePostcrossing.py
          
      - name: 提交
        id: push
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m '已更新数据' || (echo "nothing to commit" && echo "PUSH_TO_GITHUB=false" >> "$GITHUB_OUTPUT")
          git push || echo "nothing to push"
          echo "PUSH_TO_GITHUB=$PUSH_TO_GITHUB"
          
      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 8

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: src/.vuepress/dist